export class Card {
    path_id: number;
    path_url: string;
  }

export const CARDS: Card[] = [
    { path_id: 1, path_url: 'card_1.png' },
    { path_id: 2, path_url: 'card_2.png' },
    { path_id: 3, path_url: 'card_3.png' },
    { path_id: 4, path_url: 'card_4.png' },
    { path_id: 5, path_url: 'card_5.png' },
    { path_id: 6, path_url: 'card_6.png' },
    { path_id: 7, path_url: 'card_7.png' },
    { path_id: 8, path_url: 'card_8.png' },
    { path_id: 9, path_url: 'card_9.png' },
    { path_id: 10, path_url: 'card_10.png' },
    { path_id: 11, path_url: 'card_11.png' },
    { path_id: 12, path_url: 'card_12.png' },
    { path_id: 13, path_url: 'card_13.png' },
    { path_id: 14, path_url: 'card_14.png' },
    { path_id: 15, path_url: 'card_15.png' },
    { path_id: 16, path_url: 'card_16.png' },
    { path_id: 17, path_url: 'card_17.png' },
    { path_id: 18, path_url: 'card_18.png' },
    { path_id: 19, path_url: 'card_19.png' },
    { path_id: 20, path_url: 'card_20.png' },
    { path_id: 21, path_url: 'card_21.png' },
    { path_id: 22, path_url: 'card_22.png' },
    { path_id: 23, path_url: 'card_23.png' },
    { path_id: 24, path_url: 'card_24.png' },
    { path_id: 25, path_url: 'card_25.png' },
    { path_id: 26, path_url: 'card_26.png' },
    { path_id: 27, path_url: 'card_27.png' },
    { path_id: 28, path_url: 'card_28.png' },
    { path_id: 29, path_url: 'card_29.png' },
    { path_id: 30, path_url: 'card_30.png' },
    { path_id: 31, path_url: 'card_31.png' },
    { path_id: 32, path_url: 'card_32.png' },
    { path_id: 33, path_url: 'card_33.png' },
    { path_id: 34, path_url: 'card_34.png' },
    { path_id: 35, path_url: 'card_35.png' },
    { path_id: 36, path_url: 'card_36.png' },
    { path_id: 37, path_url: 'card_37.png' },
    { path_id: 38, path_url: 'card_38.png' },
    { path_id: 39, path_url: 'card_39.png' },
    { path_id: 40, path_url: 'card_40.png' },
    { path_id: 41, path_url: 'card_41.png' },
    { path_id: 42, path_url: 'card_42.png' },
    { path_id: 43, path_url: 'card_43.png' },
    { path_id: 44, path_url: 'card_44.png' },
    { path_id: 45, path_url: 'card_45.png' },
    { path_id: 46, path_url: 'card_46.png' },
    { path_id: 47, path_url: 'card_47.png' },
    { path_id: 48, path_url: 'card_48.png' },
    { path_id: 49, path_url: 'card_49.png' },
    { path_id: 50, path_url: 'card_50.png' },
    { path_id: 50, path_url: 'card_51.png' },
    { path_id: 50, path_url: 'card_52.png' },
    { path_id: 50, path_url: 'card_53.png' },
    { path_id: 50, path_url: 'card_54.png' },
    { path_id: 50, path_url: 'card_55.png' },
    { path_id: 50, path_url: 'card_56.png' },
    { path_id: 50, path_url: 'card_57.png' },
    { path_id: 50, path_url: 'card_58.png' }
];